# Generated by Django 2.1.15 on 2020-04-04 03:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('proveedores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Colaborador',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('proveedor', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, primary_key=True, serialize=False, to='proveedores.Proveedor')),
                ('estado', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Proveedores Colaboración',
                'ordering': ['proveedor'],
            },
        ),
        migrations.CreateModel(
            name='ContactoProveedor',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nombre', models.CharField(blank=True, max_length=50, null=True)),
                ('apellido', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.EmailField(max_length=254, primary_key=True, serialize=False)),
                ('en_copia', models.BooleanField(default=False)),
                ('proveedor', models.ManyToManyField(to='colaboracion.Colaborador')),
            ],
            options={
                'verbose_name_plural': 'Contactos Proveedores',
                'ordering': ['email'],
            },
        ),
    ]
