# Generated by Django 2.1.15 on 2020-04-05 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colaboracion', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactoproveedor',
            options={'ordering': ['email', 'en_copia'], 'verbose_name_plural': 'Contactos Proveedores'},
        ),
        migrations.AlterField(
            model_name='contactoproveedor',
            name='apellido',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='contactoproveedor',
            name='nombre',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
