# Generated by Django 2.1.15 on 2020-04-21 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('colaboracion', '0002_auto_20200405_0548'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactoproveedor',
            options={'ordering': ['en_copia', 'email'], 'verbose_name_plural': 'Contactos Proveedores'},
        ),
    ]
