# Generated by Django 2.1.15 on 2020-04-21 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tableros', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tablero',
            name='url',
            field=models.URLField(max_length=1000),
        ),
    ]
