# Generated by Django 2.1.15 on 2020-04-21 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tableros', '0002_auto_20200421_1749'),
    ]

    operations = [
        migrations.AddField(
            model_name='tablero',
            name='script',
            field=models.CharField(blank=True, default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='tablero',
            name='url',
            field=models.URLField(),
        ),
    ]
