# Generated by Django 2.1.15 on 2020-04-04 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id_dwh', models.IntegerField(unique=True)),
                ('codigo_pmm', models.IntegerField(unique=True)),
                ('rut', models.IntegerField(primary_key=True, serialize=False)),
                ('razon_social', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Proveedores',
                'ordering': ['razon_social'],
            },
        ),
    ]
